package blog.anirbanm.keyboard.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 08 10:47:03 IST 2018
// ---------------------------------------------------------------------
public interface KeyboardModule extends ApplicationModule {
    void keyboardAction(String keyboardActionKey);
}

