package blog.anirbanm.keyboard.model.vo;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 08 10:26:32 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVOImpl extends ViewObjectImpl {
    
    private final static ADFLogger LOGGER = ADFLogger.createADFLogger(EmployeesVOImpl.class);
    
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesVOImpl() {
    }
}

